import type { GameConfig } from './ConfigTypes';

function deepFreeze<T>(value: T): T {
  if (value === null || typeof value !== 'object' || Object.isFrozen(value)) {
    return value;
  }

  const objectValue = value as Record<string, unknown>;
  for (const propertyName of Object.getOwnPropertyNames(value)) {
    deepFreeze(objectValue[propertyName]);
  }

  return Object.freeze(value);
}

/**
 * 通用难度档数值/奖励乘数（V08-02 阶段决策 3：难度=乘数，不改变机制）。
 * normal 与 V0.5 已验证数值完全一致（乘数全 1）。
 */
const DIFFICULTY_NORMAL = {
  id: 'diff_normal',
  displayName: '普通',
  hpMultiplier: 1,
  speedMultiplier: 1,
  contactDamageMultiplier: 1,
  xpMultiplier: 1,
  rewardMultiplier: 1,
  requiredStarsOnPrevious: 0,
} as const;

const DIFFICULTY_HARD = {
  id: 'diff_hard',
  displayName: '困难',
  hpMultiplier: 2.2,
  speedMultiplier: 1.1,
  contactDamageMultiplier: 1.5,
  xpMultiplier: 1.6,
  rewardMultiplier: 1.6,
  requiredStarsOnPrevious: 1,
} as const;

const DIFFICULTY_NIGHTMARE = {
  id: 'diff_nightmare',
  displayName: '噩梦',
  hpMultiplier: 4.5,
  speedMultiplier: 1.2,
  contactDamageMultiplier: 2,
  xpMultiplier: 2.4,
  rewardMultiplier: 2.4,
  requiredStarsOnPrevious: 1,
} as const;

const STAGE_DIFFICULTIES = [DIFFICULTY_NORMAL, DIFFICULTY_HARD, DIFFICULTY_NIGHTMARE] as const;

/** The only source of MVP balance values. Runtime systems must not mutate it. */
export const INITIAL_GAME_CONFIG: GameConfig = deepFreeze<GameConfig>({
  initialStageId: 'stage_mvp_01',
  player: {
    moveSpeed: 320,
    collisionRadius: 24,
    maxHp: 20,
    invulnerableSeconds: 0.8,
  },
  monsters: [
    {
      id: 'monster_basic',
      displayName: '妖卒',
      prefabId: 'prefab_monster_basic',
      maxHp: 20,
      moveSpeed: 90,
      contactDamage: 2,
      xpValue: 1,
      collisionRadius: 24,
    },
    // V0.8 新怪（阶段决策 4：配置区分，灰盒视觉复用 prefab_monster_basic）。
    {
      id: 'monster_yaonu',
      displayName: '妖奴',
      prefabId: 'prefab_monster_basic',
      maxHp: 14,
      moveSpeed: 140,
      contactDamage: 2,
      xpValue: 1,
      collisionRadius: 20,
    },
    {
      id: 'monster_duzhu',
      displayName: '毒蛛',
      prefabId: 'prefab_monster_basic',
      maxHp: 26,
      moveSpeed: 105,
      contactDamage: 3,
      xpValue: 2,
      collisionRadius: 22,
    },
    {
      id: 'monster_shiren',
      displayName: '石人',
      prefabId: 'prefab_monster_basic',
      maxHp: 60,
      moveSpeed: 55,
      contactDamage: 4,
      xpValue: 3,
      collisionRadius: 30,
    },
  ],
  bosses: [
    {
      id: 'boss_shiyao_general',
      displayName: '噬妖妖将',
      spawnTime: 120,
      maxHp: 400,
      moveSpeed: 45,
      contactDamage: 6,
      xpValue: 30,
      collisionRadius: 40,
      radialBurst: {
        count: 12,
        damage: 8,
        burstIntervalSeconds: 5,
        enragedIntervalSeconds: 3,
      },
    },
    // V0.8 新 Boss（阶段决策 4：数值/弹幕参数区分，灰盒视觉复用 Boss prefab）。
    {
      id: 'boss_fuchao_shuyao',
      displayName: '腐潮树妖',
      spawnTime: 150,
      maxHp: 900,
      moveSpeed: 40,
      contactDamage: 8,
      xpValue: 60,
      collisionRadius: 46,
      radialBurst: {
        count: 16,
        damage: 10,
        burstIntervalSeconds: 4.5,
        enragedIntervalSeconds: 2.5,
      },
    },
    {
      id: 'boss_shiyao_lord',
      displayName: '噬妖之主',
      spawnTime: 180,
      maxHp: 2000,
      moveSpeed: 50,
      contactDamage: 12,
      xpValue: 120,
      collisionRadius: 52,
      radialBurst: {
        count: 20,
        damage: 12,
        burstIntervalSeconds: 4,
        enragedIntervalSeconds: 2,
      },
    },
  ],
  projectiles: [
    {
      id: 'projectile_boss_bullet',
      prefabId: 'prefab_flying_sword',
      speed: 240,
      lifetime: 3,
      collisionRadius: 10,
    },
    {
      id: 'projectile_sword_qi',
      prefabId: 'prefab_flying_sword',
      speed: 540,
      lifetime: 1.6,
      collisionRadius: 12,
    },
    {
      id: 'projectile_qingxiao_sword',
      prefabId: 'prefab_flying_sword',
      speed: 720,
      lifetime: 2,
      collisionRadius: 12,
    },
  ],
  weapons: [
    {
      id: 'weapon_qingxiao_sword',
      displayName: '青霄剑',
      projectileId: 'projectile_qingxiao_sword',
      baseDamage: 10,
      cooldown: 0.8,
      minCooldown: 0.2,
      projectileCount: 1,
      maxProjectileCount: 8,
      maxActiveProjectiles: 32,
      projectileSpreadDegrees: 10,
      attackRadius: 650,
      targetRetryInterval: 0.1,
    },
  ],
  pickups: [
    {
      id: 'xp_gem_basic',
      prefabId: 'prefab_xp_gem_basic',
      pickupRadius: 60,
      maxActiveCount: 100,
    },
  ],
  // V0.5 局外资源（ECONOMY.md）；灵魄按兽隔离，投放来源见 stageRewards（V08-02 扩充）。
  // 灵玉（V08-10）：唯一产出=成就分级奖励（一次性）；消费=商店稀缺商品（V08-12）。无支付/广告。
  resources: [
    { id: 'res_lingshi', displayName: '灵石', capacity: 999999 },
    { id: 'res_xiuwei', displayName: '修为', capacity: 999999 },
    { id: 'res_yaodan', displayName: '妖丹', capacity: 9999 },
    { id: 'res_lingyu', displayName: '灵玉', capacity: 9999 },
    { id: 'res_lingpo_qinglong', displayName: '青龙灵魄', capacity: 9999 },
    { id: 'res_lingpo_baihu', displayName: '白虎灵魄', capacity: 9999 },
    { id: 'res_lingpo_zhuque', displayName: '朱雀灵魄', capacity: 9999 },
    { id: 'res_lingpo_xuanwu', displayName: '玄武灵魄', capacity: 9999 },
    { id: 'res_lingpo_jiuweihu', displayName: '九尾狐灵魄', capacity: 9999 },
  ],
  gongfas: [
    {
      id: 'gongfa_sword_qi',
      title: '剑气冲击',
      description: '每 3 秒向最近目标放出穿透剑气，每层 +1 道',
      maxStacks: 5,
      weight: 1,
      effects: [{ kind: 'addSwordQi', value: 1, intervalSeconds: 3, damageFactor: 0.6 }],
    },
    {
      id: 'gongfa_ward',
      title: '护体罡气',
      description: '接触伤害每层减免 15%',
      maxStacks: 5,
      weight: 1,
      effects: [{ kind: 'contactDamageReduction', value: 0.15 }],
    },
  ],
  treasures: [
    {
      id: 'treasure_shiyao_banner',
      title: '噬妖幡',
      description: '每次击杀回复 2 点生命，每层 +2',
      maxStacks: 3,
      weight: 1,
      effects: [{ kind: 'healOnKill', value: 2 }],
    },
  ],
  eliteModifier: {
    hpMultiplier: 4,
    speedMultiplier: 0.85,
    contactDamageMultiplier: 2,
    xpMultiplier: 5,
    collisionRadiusMultiplier: 1.5,
  },
  spawnWaves: [
    {
      id: 'wave_mvp_early',
      startTime: 0,
      endTime: 180,
      spawnInterval: 1,
      batchSize: 1,
      monsters: [
        { monsterId: 'monster_basic', weight: 5 },
        { monsterId: 'monster_basic', weight: 1, elite: true },
      ],
    },
    {
      id: 'wave_mvp_late',
      startTime: 180,
      endTime: 600,
      spawnInterval: 0.6,
      batchSize: 2,
      monsters: [
        { monsterId: 'monster_basic', weight: 4 },
        { monsterId: 'monster_basic', weight: 1, elite: true },
      ],
    },
    // —— 青云外门（引入妖奴）——
    {
      id: 'wave_qingyun_02_a',
      startTime: 0,
      endTime: 240,
      spawnInterval: 0.9,
      batchSize: 1,
      monsters: [
        { monsterId: 'monster_basic', weight: 5 },
        { monsterId: 'monster_yaonu', weight: 2 },
        { monsterId: 'monster_basic', weight: 1, elite: true },
      ],
    },
    {
      id: 'wave_qingyun_02_b',
      startTime: 240,
      endTime: 480,
      spawnInterval: 0.6,
      batchSize: 2,
      monsters: [
        { monsterId: 'monster_basic', weight: 4 },
        { monsterId: 'monster_yaonu', weight: 3 },
        { monsterId: 'monster_basic', weight: 1, elite: true },
      ],
    },
    {
      id: 'wave_qingyun_03_a',
      startTime: 0,
      endTime: 240,
      spawnInterval: 0.85,
      batchSize: 1,
      monsters: [
        { monsterId: 'monster_basic', weight: 4 },
        { monsterId: 'monster_yaonu', weight: 2 },
        { monsterId: 'monster_duzhu', weight: 1 },
        { monsterId: 'monster_basic', weight: 1, elite: true },
      ],
    },
    {
      id: 'wave_qingyun_03_b',
      startTime: 240,
      endTime: 480,
      spawnInterval: 0.55,
      batchSize: 2,
      monsters: [
        { monsterId: 'monster_basic', weight: 3 },
        { monsterId: 'monster_yaonu', weight: 3 },
        { monsterId: 'monster_duzhu', weight: 2 },
        { monsterId: 'monster_duzhu', weight: 1, elite: true },
      ],
    },
    {
      id: 'wave_qingyun_04_a',
      startTime: 0,
      endTime: 270,
      spawnInterval: 0.8,
      batchSize: 2,
      monsters: [
        { monsterId: 'monster_basic', weight: 4 },
        { monsterId: 'monster_yaonu', weight: 3 },
        { monsterId: 'monster_duzhu', weight: 1 },
        { monsterId: 'monster_basic', weight: 1, elite: true },
      ],
    },
    {
      id: 'wave_qingyun_04_b',
      startTime: 270,
      endTime: 540,
      spawnInterval: 0.5,
      batchSize: 2,
      monsters: [
        { monsterId: 'monster_basic', weight: 3 },
        { monsterId: 'monster_yaonu', weight: 3 },
        { monsterId: 'monster_duzhu', weight: 2 },
        { monsterId: 'monster_duzhu', weight: 2, elite: true },
      ],
    },
    // —— 妖潮深林（毒蛛/妖奴为主，引入石人）——
    {
      id: 'wave_yaochao_01_a',
      startTime: 0,
      endTime: 240,
      spawnInterval: 0.8,
      batchSize: 2,
      monsters: [
        { monsterId: 'monster_yaonu', weight: 4 },
        { monsterId: 'monster_basic', weight: 3 },
        { monsterId: 'monster_duzhu', weight: 2 },
        { monsterId: 'monster_yaonu', weight: 1, elite: true },
      ],
    },
    {
      id: 'wave_yaochao_01_b',
      startTime: 240,
      endTime: 480,
      spawnInterval: 0.5,
      batchSize: 2,
      monsters: [
        { monsterId: 'monster_yaonu', weight: 4 },
        { monsterId: 'monster_duzhu', weight: 3 },
        { monsterId: 'monster_basic', weight: 2 },
        { monsterId: 'monster_yaonu', weight: 2, elite: true },
      ],
    },
    {
      id: 'wave_yaochao_02_a',
      startTime: 0,
      endTime: 240,
      spawnInterval: 0.8,
      batchSize: 2,
      monsters: [
        { monsterId: 'monster_basic', weight: 3 },
        { monsterId: 'monster_yaonu', weight: 3 },
        { monsterId: 'monster_duzhu', weight: 2 },
        { monsterId: 'monster_shiren', weight: 1 },
        { monsterId: 'monster_duzhu', weight: 1, elite: true },
      ],
    },
    {
      id: 'wave_yaochao_02_b',
      startTime: 240,
      endTime: 480,
      spawnInterval: 0.5,
      batchSize: 2,
      monsters: [
        { monsterId: 'monster_yaonu', weight: 3 },
        { monsterId: 'monster_duzhu', weight: 3 },
        { monsterId: 'monster_shiren', weight: 2 },
        { monsterId: 'monster_duzhu', weight: 2, elite: true },
      ],
    },
    {
      id: 'wave_yaochao_03_a',
      startTime: 0,
      endTime: 255,
      spawnInterval: 0.75,
      batchSize: 2,
      monsters: [
        { monsterId: 'monster_yaonu', weight: 4 },
        { monsterId: 'monster_duzhu', weight: 3 },
        { monsterId: 'monster_shiren', weight: 2 },
        { monsterId: 'monster_yaonu', weight: 1, elite: true },
      ],
    },
    {
      id: 'wave_yaochao_03_b',
      startTime: 255,
      endTime: 510,
      spawnInterval: 0.45,
      batchSize: 2,
      monsters: [
        { monsterId: 'monster_duzhu', weight: 4 },
        { monsterId: 'monster_shiren', weight: 3 },
        { monsterId: 'monster_yaonu', weight: 3 },
        { monsterId: 'monster_duzhu', weight: 2, elite: true },
      ],
    },
    {
      id: 'wave_yaochao_04_a',
      startTime: 0,
      endTime: 270,
      spawnInterval: 0.7,
      batchSize: 2,
      monsters: [
        { monsterId: 'monster_yaonu', weight: 4 },
        { monsterId: 'monster_duzhu', weight: 3 },
        { monsterId: 'monster_shiren', weight: 2 },
        { monsterId: 'monster_duzhu', weight: 1, elite: true },
      ],
    },
    {
      id: 'wave_yaochao_04_b',
      startTime: 270,
      endTime: 540,
      spawnInterval: 0.45,
      batchSize: 3,
      monsters: [
        { monsterId: 'monster_duzhu', weight: 4 },
        { monsterId: 'monster_shiren', weight: 3 },
        { monsterId: 'monster_yaonu', weight: 2 },
        { monsterId: 'monster_shiren', weight: 2, elite: true },
      ],
    },
    // —— 噬妖巢穴（石人/毒蛛重压）——
    {
      id: 'wave_shiyao_01_a',
      startTime: 0,
      endTime: 255,
      spawnInterval: 0.7,
      batchSize: 2,
      monsters: [
        { monsterId: 'monster_duzhu', weight: 4 },
        { monsterId: 'monster_shiren', weight: 3 },
        { monsterId: 'monster_yaonu', weight: 3 },
        { monsterId: 'monster_duzhu', weight: 1, elite: true },
      ],
    },
    {
      id: 'wave_shiyao_01_b',
      startTime: 255,
      endTime: 510,
      spawnInterval: 0.45,
      batchSize: 3,
      monsters: [
        { monsterId: 'monster_shiren', weight: 4 },
        { monsterId: 'monster_duzhu', weight: 3 },
        { monsterId: 'monster_yaonu', weight: 3 },
        { monsterId: 'monster_shiren', weight: 2, elite: true },
      ],
    },
    {
      id: 'wave_shiyao_02_a',
      startTime: 0,
      endTime: 255,
      spawnInterval: 0.65,
      batchSize: 2,
      monsters: [
        { monsterId: 'monster_shiren', weight: 4 },
        { monsterId: 'monster_duzhu', weight: 4 },
        { monsterId: 'monster_yaonu', weight: 2 },
        { monsterId: 'monster_shiren', weight: 1, elite: true },
      ],
    },
    {
      id: 'wave_shiyao_02_b',
      startTime: 255,
      endTime: 510,
      spawnInterval: 0.4,
      batchSize: 3,
      monsters: [
        { monsterId: 'monster_shiren', weight: 4 },
        { monsterId: 'monster_duzhu', weight: 4 },
        { monsterId: 'monster_shiren', weight: 2, elite: true },
      ],
    },
    {
      id: 'wave_shiyao_03_a',
      startTime: 0,
      endTime: 270,
      spawnInterval: 0.6,
      batchSize: 3,
      monsters: [
        { monsterId: 'monster_shiren', weight: 4 },
        { monsterId: 'monster_duzhu', weight: 4 },
        { monsterId: 'monster_yaonu', weight: 3 },
        { monsterId: 'monster_duzhu', weight: 1, elite: true },
      ],
    },
    {
      id: 'wave_shiyao_03_b',
      startTime: 270,
      endTime: 540,
      spawnInterval: 0.4,
      batchSize: 3,
      monsters: [
        { monsterId: 'monster_shiren', weight: 5 },
        { monsterId: 'monster_duzhu', weight: 4 },
        { monsterId: 'monster_shiren', weight: 2, elite: true },
      ],
    },
    {
      id: 'wave_shiyao_04_a',
      startTime: 0,
      endTime: 300,
      spawnInterval: 0.6,
      batchSize: 3,
      monsters: [
        { monsterId: 'monster_shiren', weight: 4 },
        { monsterId: 'monster_duzhu', weight: 4 },
        { monsterId: 'monster_yaonu', weight: 3 },
        { monsterId: 'monster_duzhu', weight: 1, elite: true },
      ],
    },
    {
      id: 'wave_shiyao_04_b',
      startTime: 300,
      endTime: 600,
      spawnInterval: 0.35,
      batchSize: 3,
      monsters: [
        { monsterId: 'monster_shiren', weight: 5 },
        { monsterId: 'monster_duzhu', weight: 4 },
        { monsterId: 'monster_shiren', weight: 2, elite: true },
      ],
    },
  ],
  // —— 章节（V08-02）：3 章节 × 4 关；章内前一关通关解锁下一关（V08-03 实装）。 ——
  chapters: [
    {
      id: 'chapter_qingyun',
      displayName: '青云外门',
      stageIds: ['stage_mvp_01', 'stage_qingyun_02', 'stage_qingyun_03', 'stage_qingyun_04'],
      requiredChapterId: null,
    },
    {
      id: 'chapter_yaochao',
      displayName: '妖潮深林',
      stageIds: ['stage_yaochao_01', 'stage_yaochao_02', 'stage_yaochao_03', 'stage_yaochao_04'],
      requiredChapterId: 'chapter_qingyun',
    },
    {
      id: 'chapter_shiyao',
      displayName: '噬妖巢穴',
      stageIds: ['stage_shiyao_01', 'stage_shiyao_02', 'stage_shiyao_03', 'stage_shiyao_04'],
      requiredChapterId: 'chapter_yaochao',
    },
  ],
  stages: [
    {
      id: 'stage_mvp_01',
      displayName: '外门第一试',
      chapterId: 'chapter_qingyun',
      duration: 600,
      activeMonsterSoftCap: 120,
      activeMonsterHardCap: 180,
      spawnMinRadius: 600,
      spawnMaxRadius: 850,
      playArea: {
        minX: -1200,
        maxX: 1200,
        minY: -800,
        maxY: 800,
      },
      waveIds: ['wave_mvp_early', 'wave_mvp_late'],
      bossId: 'boss_shiyao_general',
      starConditions: [
        { kind: 'clear' },
        { kind: 'hpRatioAbove', ratio: 0.5 },
        { kind: 'hitTakenAtMost', count: 30 },
      ],
      difficulties: STAGE_DIFFICULTIES,
      milestoneRewards: {
        firstClear: { accountXp: 30, resources: { res_lingshi: 100 } },
        perStar: [
          { accountXp: 12, resources: { res_lingshi: 50 } },
          { accountXp: 18, resources: { res_lingshi: 75 } },
          { accountXp: 30, resources: { res_lingshi: 125 } },
        ],
      },
    },
    {
      id: 'stage_qingyun_02',
      displayName: '外门妖奴潮',
      chapterId: 'chapter_qingyun',
      duration: 480,
      activeMonsterSoftCap: 120,
      activeMonsterHardCap: 180,
      spawnMinRadius: 600,
      spawnMaxRadius: 850,
      playArea: {
        minX: -1200,
        maxX: 1200,
        minY: -800,
        maxY: 800,
      },
      waveIds: ['wave_qingyun_02_a', 'wave_qingyun_02_b'],
      bossId: null,
      starConditions: [
        { kind: 'clear' },
        { kind: 'hpRatioAbove', ratio: 0.6 },
        { kind: 'timeUnder', seconds: 420 },
      ],
      difficulties: STAGE_DIFFICULTIES,
      milestoneRewards: {
        firstClear: { accountXp: 34, resources: { res_lingshi: 120 } },
        perStar: [
          { accountXp: 14, resources: { res_lingshi: 60 } },
          { accountXp: 20, resources: { res_lingshi: 90 } },
          { accountXp: 34, resources: { res_lingshi: 150 } },
        ],
      },
    },
    {
      id: 'stage_qingyun_03',
      displayName: '毒蛛林道',
      chapterId: 'chapter_qingyun',
      duration: 480,
      activeMonsterSoftCap: 120,
      activeMonsterHardCap: 180,
      spawnMinRadius: 600,
      spawnMaxRadius: 850,
      playArea: {
        minX: -1200,
        maxX: 1200,
        minY: -800,
        maxY: 800,
      },
      waveIds: ['wave_qingyun_03_a', 'wave_qingyun_03_b'],
      bossId: null,
      starConditions: [
        { kind: 'clear' },
        { kind: 'hitTakenAtMost', count: 25 },
        { kind: 'timeUnder', seconds: 400 },
      ],
      difficulties: STAGE_DIFFICULTIES,
      milestoneRewards: {
        firstClear: { accountXp: 38, resources: { res_lingshi: 145 } },
        perStar: [
          { accountXp: 15, resources: { res_lingshi: 72 } },
          { accountXp: 23, resources: { res_lingshi: 108 } },
          { accountXp: 38, resources: { res_lingshi: 180 } },
        ],
      },
    },
    {
      id: 'stage_qingyun_04',
      displayName: '妖将压境',
      chapterId: 'chapter_qingyun',
      duration: 540,
      activeMonsterSoftCap: 120,
      activeMonsterHardCap: 180,
      spawnMinRadius: 600,
      spawnMaxRadius: 850,
      playArea: {
        minX: -1200,
        maxX: 1200,
        minY: -800,
        maxY: 800,
      },
      waveIds: ['wave_qingyun_04_a', 'wave_qingyun_04_b'],
      bossId: 'boss_shiyao_general',
      starConditions: [
        { kind: 'clear' },
        { kind: 'hpRatioAbove', ratio: 0.5 },
        { kind: 'hitTakenAtMost', count: 40 },
      ],
      difficulties: STAGE_DIFFICULTIES,
      milestoneRewards: {
        firstClear: { accountXp: 44, resources: { res_lingshi: 175 } },
        perStar: [
          { accountXp: 18, resources: { res_lingshi: 88 } },
          { accountXp: 26, resources: { res_lingshi: 130 } },
          { accountXp: 44, resources: { res_lingshi: 220 } },
        ],
      },
    },
    {
      id: 'stage_yaochao_01',
      displayName: '深林边缘',
      chapterId: 'chapter_yaochao',
      duration: 480,
      activeMonsterSoftCap: 130,
      activeMonsterHardCap: 190,
      spawnMinRadius: 600,
      spawnMaxRadius: 850,
      playArea: {
        minX: -1200,
        maxX: 1200,
        minY: -800,
        maxY: 800,
      },
      waveIds: ['wave_yaochao_01_a', 'wave_yaochao_01_b'],
      bossId: null,
      starConditions: [
        { kind: 'clear' },
        { kind: 'hpRatioAbove', ratio: 0.6 },
        { kind: 'timeUnder', seconds: 400 },
      ],
      difficulties: STAGE_DIFFICULTIES,
      milestoneRewards: {
        firstClear: { accountXp: 52, resources: { res_lingshi: 210 } },
        perStar: [
          { accountXp: 21, resources: { res_lingshi: 105 } },
          { accountXp: 31, resources: { res_lingshi: 158 } },
          { accountXp: 52, resources: { res_lingshi: 262 } },
        ],
      },
    },
    {
      id: 'stage_yaochao_02',
      displayName: '石人古道',
      chapterId: 'chapter_yaochao',
      duration: 480,
      activeMonsterSoftCap: 130,
      activeMonsterHardCap: 190,
      spawnMinRadius: 600,
      spawnMaxRadius: 850,
      playArea: {
        minX: -1200,
        maxX: 1200,
        minY: -800,
        maxY: 800,
      },
      waveIds: ['wave_yaochao_02_a', 'wave_yaochao_02_b'],
      bossId: null,
      starConditions: [
        { kind: 'clear' },
        { kind: 'hitTakenAtMost', count: 35 },
        { kind: 'hpRatioAbove', ratio: 0.5 },
      ],
      difficulties: STAGE_DIFFICULTIES,
      milestoneRewards: {
        firstClear: { accountXp: 60, resources: { res_lingshi: 250 } },
        perStar: [
          { accountXp: 24, resources: { res_lingshi: 125 } },
          { accountXp: 36, resources: { res_lingshi: 188 } },
          { accountXp: 60, resources: { res_lingshi: 312 } },
        ],
      },
    },
    {
      id: 'stage_yaochao_03',
      displayName: '腐潮蔓延',
      chapterId: 'chapter_yaochao',
      duration: 510,
      activeMonsterSoftCap: 130,
      activeMonsterHardCap: 190,
      spawnMinRadius: 600,
      spawnMaxRadius: 850,
      playArea: {
        minX: -1200,
        maxX: 1200,
        minY: -800,
        maxY: 800,
      },
      waveIds: ['wave_yaochao_03_a', 'wave_yaochao_03_b'],
      bossId: null,
      starConditions: [
        { kind: 'clear' },
        { kind: 'timeUnder', seconds: 430 },
        { kind: 'hitTakenAtMost', count: 40 },
      ],
      difficulties: STAGE_DIFFICULTIES,
      milestoneRewards: {
        firstClear: { accountXp: 68, resources: { res_lingshi: 295 } },
        perStar: [
          { accountXp: 27, resources: { res_lingshi: 148 } },
          { accountXp: 41, resources: { res_lingshi: 222 } },
          { accountXp: 68, resources: { res_lingshi: 368 } },
        ],
      },
    },
    {
      id: 'stage_yaochao_04',
      displayName: '树妖之巢',
      chapterId: 'chapter_yaochao',
      duration: 540,
      activeMonsterSoftCap: 130,
      activeMonsterHardCap: 190,
      spawnMinRadius: 600,
      spawnMaxRadius: 850,
      playArea: {
        minX: -1200,
        maxX: 1200,
        minY: -800,
        maxY: 800,
      },
      waveIds: ['wave_yaochao_04_a', 'wave_yaochao_04_b'],
      bossId: 'boss_fuchao_shuyao',
      starConditions: [
        { kind: 'clear' },
        { kind: 'hpRatioAbove', ratio: 0.5 },
        { kind: 'timeUnder', seconds: 480 },
      ],
      difficulties: STAGE_DIFFICULTIES,
      milestoneRewards: {
        firstClear: { accountXp: 78, resources: { res_lingshi: 350 } },
        perStar: [
          { accountXp: 31, resources: { res_lingshi: 175 } },
          { accountXp: 47, resources: { res_lingshi: 262 } },
          { accountXp: 78, resources: { res_lingshi: 438 } },
        ],
      },
    },
    {
      id: 'stage_shiyao_01',
      displayName: '巢穴外沿',
      chapterId: 'chapter_shiyao',
      duration: 510,
      activeMonsterSoftCap: 140,
      activeMonsterHardCap: 200,
      spawnMinRadius: 600,
      spawnMaxRadius: 850,
      playArea: {
        minX: -1200,
        maxX: 1200,
        minY: -800,
        maxY: 800,
      },
      waveIds: ['wave_shiyao_01_a', 'wave_shiyao_01_b'],
      bossId: null,
      starConditions: [
        { kind: 'clear' },
        { kind: 'hpRatioAbove', ratio: 0.6 },
        { kind: 'hitTakenAtMost', count: 45 },
      ],
      difficulties: STAGE_DIFFICULTIES,
      milestoneRewards: {
        firstClear: { accountXp: 88, resources: { res_lingshi: 410 } },
        perStar: [
          { accountXp: 35, resources: { res_lingshi: 205 } },
          { accountXp: 53, resources: { res_lingshi: 308 } },
          { accountXp: 88, resources: { res_lingshi: 512 } },
        ],
      },
    },
    {
      id: 'stage_shiyao_02',
      displayName: '噬妖回廊',
      chapterId: 'chapter_shiyao',
      duration: 510,
      activeMonsterSoftCap: 140,
      activeMonsterHardCap: 200,
      spawnMinRadius: 600,
      spawnMaxRadius: 850,
      playArea: {
        minX: -1200,
        maxX: 1200,
        minY: -800,
        maxY: 800,
      },
      waveIds: ['wave_shiyao_02_a', 'wave_shiyao_02_b'],
      bossId: null,
      starConditions: [
        { kind: 'clear' },
        { kind: 'hitTakenAtMost', count: 50 },
        { kind: 'timeUnder', seconds: 450 },
      ],
      difficulties: STAGE_DIFFICULTIES,
      milestoneRewards: {
        firstClear: { accountXp: 100, resources: { res_lingshi: 480 } },
        perStar: [
          { accountXp: 40, resources: { res_lingshi: 240 } },
          { accountXp: 60, resources: { res_lingshi: 360 } },
          { accountXp: 100, resources: { res_lingshi: 600 } },
        ],
      },
    },
    {
      id: 'stage_shiyao_03',
      displayName: '妖群深处',
      chapterId: 'chapter_shiyao',
      duration: 540,
      activeMonsterSoftCap: 140,
      activeMonsterHardCap: 200,
      spawnMinRadius: 600,
      spawnMaxRadius: 850,
      playArea: {
        minX: -1200,
        maxX: 1200,
        minY: -800,
        maxY: 800,
      },
      waveIds: ['wave_shiyao_03_a', 'wave_shiyao_03_b'],
      bossId: null,
      starConditions: [
        { kind: 'clear' },
        { kind: 'hpRatioAbove', ratio: 0.5 },
        { kind: 'hitTakenAtMost', count: 55 },
      ],
      difficulties: STAGE_DIFFICULTIES,
      milestoneRewards: {
        firstClear: { accountXp: 112, resources: { res_lingshi: 555 } },
        perStar: [
          { accountXp: 45, resources: { res_lingshi: 278 } },
          { accountXp: 67, resources: { res_lingshi: 416 } },
          { accountXp: 112, resources: { res_lingshi: 694 } },
        ],
      },
    },
    {
      id: 'stage_shiyao_04',
      displayName: '噬妖之主',
      chapterId: 'chapter_shiyao',
      duration: 600,
      activeMonsterSoftCap: 140,
      activeMonsterHardCap: 200,
      spawnMinRadius: 600,
      spawnMaxRadius: 850,
      playArea: {
        minX: -1200,
        maxX: 1200,
        minY: -800,
        maxY: 800,
      },
      waveIds: ['wave_shiyao_04_a', 'wave_shiyao_04_b'],
      bossId: 'boss_shiyao_lord',
      starConditions: [
        { kind: 'clear' },
        { kind: 'hpRatioAbove', ratio: 0.6 },
        { kind: 'timeUnder', seconds: 540 },
      ],
      difficulties: STAGE_DIFFICULTIES,
      milestoneRewards: {
        firstClear: { accountXp: 128, resources: { res_lingshi: 640 } },
        perStar: [
          { accountXp: 51, resources: { res_lingshi: 320 } },
          { accountXp: 77, resources: { res_lingshi: 480 } },
          { accountXp: 128, resources: { res_lingshi: 800 } },
        ],
      },
    },
  ],
  levelCurve: [
    { level: 1, requiredXp: 5 },
    { level: 2, requiredXp: 8 },
    { level: 3, requiredXp: 12 },
    { level: 4, requiredXp: 17 },
    { level: 5, requiredXp: 23 },
    { level: 6, requiredXp: 30 },
    { level: 7, requiredXp: 38 },
    { level: 8, requiredXp: 47 },
    { level: 9, requiredXp: 57 },
    { level: 10, requiredXp: 68 },
  ],
  // 账号玩家等级曲线（V0.5 局外成长，与局内战斗等级无关）；满级策略=溢出保留。
  // 曲线长度即满级（当前 20 级，与 V05-05 法器等级配置上限对齐）。
  playerLevel: {
    levelCurve: [
      { level: 1, requiredXp: 60 },
      { level: 2, requiredXp: 80 },
      { level: 3, requiredXp: 105 },
      { level: 4, requiredXp: 135 },
      { level: 5, requiredXp: 170 },
      { level: 6, requiredXp: 215 },
      { level: 7, requiredXp: 265 },
      { level: 8, requiredXp: 325 },
      { level: 9, requiredXp: 395 },
      { level: 10, requiredXp: 475 },
      { level: 11, requiredXp: 570 },
      { level: 12, requiredXp: 680 },
      { level: 13, requiredXp: 810 },
      { level: 14, requiredXp: 960 },
      { level: 15, requiredXp: 1140 },
      { level: 16, requiredXp: 1350 },
      { level: 17, requiredXp: 1600 },
      { level: 18, requiredXp: 1900 },
      { level: 19, requiredXp: 2250 },
      { level: 20, requiredXp: 2650 },
    ],
  },
  // 大境界（V0.5 局外成长，PROGRESSION.md）：小境界推进消耗 res_xiuwei（走经济事务），
  // 大境界突破消耗修为+妖丹并有玩家等级门槛，无失败机制。
  realms: [
    {
      id: 'realm_lianqi',
      displayName: '练气',
      subRealmCosts: [30, 36, 43, 52, 62, 74, 89, 107, 128],
      maxHpBonus: 0,
      breakthrough: {
        xiuweiCost: 300,
        materialId: 'res_yaodan',
        materialCost: 4,
        requiredPlayerLevel: 5,
      },
    },
    {
      id: 'realm_zhuji',
      displayName: '筑基',
      subRealmCosts: [60, 72, 86, 103, 124, 149, 179, 214, 257],
      maxHpBonus: 4,
      breakthrough: {
        xiuweiCost: 500,
        materialId: 'res_yaodan',
        materialCost: 8,
        requiredPlayerLevel: 10,
      },
    },
    {
      id: 'realm_jindan',
      displayName: '金丹',
      subRealmCosts: [120, 144, 173, 207, 249, 299, 358, 430, 516],
      maxHpBonus: 8,
      breakthrough: null,
    },
  ],
  // 法器局外培养（V0.5，PROGRESSION.md）：等级上限与玩家等级取小。
  weaponGrowth: [
    {
      weaponId: 'weapon_qingxiao_sword',
      maxLevel: 20,
      levelUpCosts: [
        80, 95, 112, 132, 156, 184, 217, 256, 302, 357,
        421, 497, 586, 692, 816, 963, 1137, 1341, 1583,
      ],
      damagePerLevel: 2,
      ultimateIds: [],
    },
  ],
  // 灵兽（V0.5 局外成长，PROGRESSION.md）：青龙默认解锁；其余四兽解锁需自身灵魄，
  // 灵魄投放来源见 stageRewards（V08-02 起各章分级投放）。
  beasts: [
    {
      id: 'beast_qinglong',
      displayName: '青龙',
      soulResourceId: 'res_lingpo_qinglong',
      unlockSoulCost: 0,
      levelUpCosts: [50, 60, 72, 86, 103, 124, 149, 179, 214],
      starUpCosts: [5, 10, 20, 40, 80],
      skill: { kind: 'damageNearest', intervalSeconds: 6, damage: 8, projectileCount: 1 },
      skillDescription: '出战时每 6 秒向最近的敌人喷吐一颗灵弹（伤害 8）',
    },
    {
      id: 'beast_baihu',
      displayName: '白虎',
      soulResourceId: 'res_lingpo_baihu',
      unlockSoulCost: 10,
      levelUpCosts: [50, 60, 72, 86, 103, 124, 149, 179, 214],
      starUpCosts: [5, 10, 20, 40, 80],
      skill: { kind: 'damageNearest', intervalSeconds: 8, damage: 12, projectileCount: 1 },
      skillDescription: '出战时每 8 秒扑击最近的敌人（伤害 12）',
    },
    {
      id: 'beast_zhuque',
      displayName: '朱雀',
      soulResourceId: 'res_lingpo_zhuque',
      unlockSoulCost: 10,
      levelUpCosts: [50, 60, 72, 86, 103, 124, 149, 179, 214],
      starUpCosts: [5, 10, 20, 40, 80],
      skill: { kind: 'damageNearest', intervalSeconds: 10, damage: 18, projectileCount: 1 },
      skillDescription: '出战时每 10 秒焚击最近的敌人（伤害 18）',
    },
    {
      id: 'beast_xuanwu',
      displayName: '玄武',
      soulResourceId: 'res_lingpo_xuanwu',
      unlockSoulCost: 10,
      levelUpCosts: [50, 60, 72, 86, 103, 124, 149, 179, 214],
      starUpCosts: [5, 10, 20, 40, 80],
      skill: { kind: 'heal', intervalSeconds: 12, value: 3 },
      skillDescription: '出战时每 12 秒为玩家回复 3 点生命',
    },
    {
      id: 'beast_jiuweihu',
      displayName: '九尾狐',
      soulResourceId: 'res_lingpo_jiuweihu',
      unlockSoulCost: 10,
      levelUpCosts: [50, 60, 72, 86, 103, 124, 149, 179, 214],
      starUpCosts: [5, 10, 20, 40, 80],
      skill: { kind: 'damageNearest', intervalSeconds: 9, damage: 5, projectileCount: 2 },
      skillDescription: '出战时每 9 秒放出两道魅惑弹（各伤害 5）',
    },
  ],
  // 结算奖励（V0.8 产出表基础值 = 普通难度胜利全额）：失败/中止保留 50%（逐项向下取整）。
  // 困难/噩梦按难度 rewardMultiplier 逐项相乘后向下取整（V08-03 装配接入）。
  stageRewards: [
    {
      stageId: 'stage_mvp_01',
      accountXp: 30,
      resources: {
        res_lingshi: 100,
        res_xiuwei: 30,
        res_yaodan: 1,
        res_lingpo_qinglong: 2,
      },
      defeatRatio: 0.5,
      abortRatio: 0.5,
    },
    {
      stageId: 'stage_qingyun_02',
      accountXp: 34,
      resources: {
        res_lingshi: 120,
        res_xiuwei: 34,
        res_yaodan: 1,
        res_lingpo_qinglong: 2,
      },
      defeatRatio: 0.5,
      abortRatio: 0.5,
    },
    {
      stageId: 'stage_qingyun_03',
      accountXp: 38,
      resources: {
        res_lingshi: 145,
        res_xiuwei: 38,
        res_yaodan: 1,
        res_lingpo_qinglong: 2,
      },
      defeatRatio: 0.5,
      abortRatio: 0.5,
    },
    {
      stageId: 'stage_qingyun_04',
      accountXp: 44,
      resources: {
        res_lingshi: 175,
        res_xiuwei: 44,
        res_yaodan: 2,
        res_lingpo_baihu: 2,
      },
      defeatRatio: 0.5,
      abortRatio: 0.5,
    },
    {
      stageId: 'stage_yaochao_01',
      accountXp: 52,
      resources: {
        res_lingshi: 210,
        res_xiuwei: 52,
        res_yaodan: 2,
        res_lingpo_baihu: 3,
      },
      defeatRatio: 0.5,
      abortRatio: 0.5,
    },
    {
      stageId: 'stage_yaochao_02',
      accountXp: 60,
      resources: {
        res_lingshi: 250,
        res_xiuwei: 60,
        res_yaodan: 2,
        res_lingpo_baihu: 3,
      },
      defeatRatio: 0.5,
      abortRatio: 0.5,
    },
    {
      stageId: 'stage_yaochao_03',
      accountXp: 68,
      resources: {
        res_lingshi: 295,
        res_xiuwei: 68,
        res_yaodan: 3,
        res_lingpo_zhuque: 2,
      },
      defeatRatio: 0.5,
      abortRatio: 0.5,
    },
    {
      stageId: 'stage_yaochao_04',
      accountXp: 78,
      resources: {
        res_lingshi: 350,
        res_xiuwei: 78,
        res_yaodan: 3,
        res_lingpo_zhuque: 3,
      },
      defeatRatio: 0.5,
      abortRatio: 0.5,
    },
    {
      stageId: 'stage_shiyao_01',
      accountXp: 88,
      resources: {
        res_lingshi: 410,
        res_xiuwei: 88,
        res_yaodan: 3,
        res_lingpo_xuanwu: 2,
      },
      defeatRatio: 0.5,
      abortRatio: 0.5,
    },
    {
      stageId: 'stage_shiyao_02',
      accountXp: 100,
      resources: {
        res_lingshi: 480,
        res_xiuwei: 100,
        res_yaodan: 4,
        res_lingpo_xuanwu: 3,
      },
      defeatRatio: 0.5,
      abortRatio: 0.5,
    },
    {
      stageId: 'stage_shiyao_03',
      accountXp: 112,
      resources: {
        res_lingshi: 555,
        res_xiuwei: 112,
        res_yaodan: 4,
        res_lingpo_jiuweihu: 2,
      },
      defeatRatio: 0.5,
      abortRatio: 0.5,
    },
    {
      stageId: 'stage_shiyao_04',
      accountXp: 128,
      resources: {
        res_lingshi: 640,
        res_xiuwei: 128,
        res_yaodan: 5,
        res_lingpo_jiuweihu: 3,
      },
      defeatRatio: 0.5,
      abortRatio: 0.5,
    },
  ],
  // 任务初始表（V08-08）：主线引导链 + 每日/每周循环，全部由既有领域事件驱动
  // （monsterDied/battleFinished/experienceCollected/levelUpResolved/经济 spend）。
  tasks: [
    {
      id: 'task_main_01',
      displayName: '初入修行',
      description: '击败 20 只妖怪',
      period: 'main',
      condition: { kind: 'killCount', target: 20 },
      reward: { accountXp: 20, resources: { res_lingshi: 80 } },
      prerequisiteTaskId: null,
    },
    {
      id: 'task_main_02',
      displayName: '剑意初成',
      description: '局内升级 3 次',
      period: 'main',
      condition: { kind: 'levelUpCount', target: 3 },
      reward: { accountXp: 20, resources: { res_lingshi: 100 } },
      prerequisiteTaskId: 'task_main_01',
    },
    {
      id: 'task_main_03',
      displayName: '首胜',
      description: '取得 1 次关卡胜利',
      period: 'main',
      condition: { kind: 'clearCount', target: 1 },
      reward: { accountXp: 30, resources: { res_xiuwei: 40 } },
      prerequisiteTaskId: 'task_main_02',
    },
    {
      id: 'task_main_04',
      displayName: '吐纳凝气',
      description: '拾取 150 点经验',
      period: 'main',
      condition: { kind: 'collectXp', target: 150 },
      reward: { accountXp: 30, resources: { res_yaodan: 2 } },
      prerequisiteTaskId: 'task_main_03',
    },
    {
      id: 'task_main_05',
      displayName: '淬剑养魂',
      description: '累计消耗 300 灵石',
      period: 'main',
      condition: { kind: 'spendResource', resourceId: 'res_lingshi', target: 300 },
      reward: { accountXp: 40, resources: { res_lingshi: 150 } },
      prerequisiteTaskId: 'task_main_04',
    },
    {
      id: 'task_main_06',
      displayName: '连战连捷',
      description: '取得 5 次关卡胜利',
      period: 'main',
      condition: { kind: 'clearCount', target: 5 },
      reward: { accountXp: 50, resources: { res_xiuwei: 100 } },
      prerequisiteTaskId: 'task_main_05',
    },
    {
      id: 'task_main_07',
      displayName: '妖潮渐起',
      description: '击败 500 只妖怪',
      period: 'main',
      condition: { kind: 'killCount', target: 500 },
      reward: { accountXp: 80, resources: { res_lingshi: 300 } },
      prerequisiteTaskId: 'task_main_06',
    },
    {
      id: 'task_daily_kill',
      displayName: '每日除妖',
      description: '击败 60 只妖怪',
      period: 'daily',
      condition: { kind: 'killCount', target: 60 },
      reward: { accountXp: 0, resources: { res_lingshi: 60, res_xiuwei: 20 } },
      prerequisiteTaskId: null,
    },
    {
      id: 'task_daily_clear',
      displayName: '每日历练',
      description: '完成 1 次关卡（胜利）',
      period: 'daily',
      condition: { kind: 'clearCount', target: 1 },
      reward: { accountXp: 0, resources: { res_lingshi: 80 } },
      prerequisiteTaskId: null,
    },
    {
      id: 'task_daily_xp',
      displayName: '每日吐纳',
      description: '拾取 120 点经验',
      period: 'daily',
      condition: { kind: 'collectXp', target: 120 },
      reward: { accountXp: 0, resources: { res_xiuwei: 25 } },
      prerequisiteTaskId: null,
    },
    {
      id: 'task_weekly_kill',
      displayName: '每周扫荡',
      description: '击败 400 只妖怪',
      period: 'weekly',
      condition: { kind: 'killCount', target: 400 },
      reward: { accountXp: 0, resources: { res_lingshi: 300 } },
      prerequisiteTaskId: null,
    },
    {
      id: 'task_weekly_clear',
      displayName: '每周突破',
      description: '取得 8 次关卡胜利',
      period: 'weekly',
      condition: { kind: 'clearCount', target: 8 },
      reward: { accountXp: 0, resources: { res_xiuwei: 150 } },
      prerequisiteTaskId: null,
    },
    {
      id: 'task_weekly_spend',
      displayName: '每周挥金',
      description: '累计消耗 1500 灵石',
      period: 'weekly',
      condition: { kind: 'spendResource', resourceId: 'res_lingshi', target: 1500 },
      reward: { accountXp: 0, resources: { res_yaodan: 3 } },
      prerequisiteTaskId: null,
    },
  ],
  // 成就初始表（V0.8，四类）：永久累计 + 分级阶段；灵玉随阶段奖励首次投放。
  achievements: [
    {
      id: 'ach_slayer',
      displayName: '斩妖除魔',
      description: '累计击败妖怪',
      condition: { kind: 'killCount' },
      tiers: [
        { target: 100, reward: { accountXp: 20, resources: { res_lingyu: 10, res_lingshi: 200 } } },
        { target: 1000, reward: { accountXp: 60, resources: { res_lingyu: 30, res_lingshi: 600 } } },
        { target: 5000, reward: { accountXp: 150, resources: { res_lingyu: 100, res_lingshi: 2000 } } },
      ],
      hidden: false,
    },
    {
      id: 'ach_victor',
      displayName: '百战不殆',
      description: '取得关卡胜利',
      condition: { kind: 'clearCount' },
      tiers: [
        { target: 3, reward: { accountXp: 20, resources: { res_lingyu: 10 } } },
        { target: 20, reward: { accountXp: 60, resources: { res_lingyu: 30 } } },
        { target: 80, reward: { accountXp: 150, resources: { res_lingyu: 100 } } },
      ],
      hidden: false,
    },
    {
      id: 'ach_collector',
      displayName: '吐纳凝魂',
      description: '累计拾取经验',
      condition: { kind: 'collectXp' },
      tiers: [
        { target: 500, reward: { accountXp: 20, resources: { res_lingyu: 10 } } },
        { target: 5000, reward: { accountXp: 60, resources: { res_lingyu: 30 } } },
        { target: 20000, reward: { accountXp: 150, resources: { res_lingyu: 100 } } },
      ],
      hidden: false,
    },
    {
      id: 'ach_cultivator',
      displayName: '日进斗精',
      description: '局内升级次数',
      condition: { kind: 'levelUpCount' },
      tiers: [
        { target: 10, reward: { accountXp: 20, resources: { res_lingyu: 10 } } },
        { target: 50, reward: { accountXp: 60, resources: { res_lingyu: 30 } } },
        { target: 200, reward: { accountXp: 150, resources: { res_lingyu: 100 } } },
      ],
      hidden: false,
    },
    {
      id: 'ach_patron',
      displayName: '挥金如土',
      description: '累计消耗灵石',
      condition: { kind: 'spendResource', resourceId: 'res_lingshi' },
      tiers: [
        { target: 500, reward: { accountXp: 20, resources: { res_lingyu: 10 } } },
        { target: 5000, reward: { accountXp: 60, resources: { res_lingyu: 30 } } },
        { target: 20000, reward: { accountXp: 150, resources: { res_lingyu: 100 } } },
      ],
      hidden: false,
    },
    {
      id: 'ach_conqueror',
      displayName: '秘境征服者',
      description: '？？？（隐藏成就）',
      condition: { kind: 'clearCount' },
      tiers: [
        { target: 30, reward: { accountXp: 100, resources: { res_lingyu: 50 } } },
        { target: 120, reward: { accountXp: 300, resources: { res_lingyu: 150 } } },
      ],
      hidden: true,
    },
  ],
  // 商店初始表（V0.8，灰盒）：常用补给按日刷新（灵石定价）；稀缺珍品永久限购（灵玉定价，
  // 消费成就投放的灵玉）。购买计数按 dayKey 惰性重置（V08-12）。
  shopGroups: [
    {
      id: 'shop_group_daily',
      displayName: '常用补给（每日刷新）',
      itemIds: [
        'shop_pill_small',
        'shop_yaodan_box',
        'shop_lingpo_baihu',
        'shop_lingpo_zhuque',
        'shop_lingpo_xuanwu',
        'shop_lingpo_jiuweihu',
      ],
    },
    {
      id: 'shop_group_rare',
      displayName: '稀缺珍品（灵玉兑换）',
      itemIds: ['shop_lingshi_pack', 'shop_yaodan_essence'],
    },
  ],
  shopItems: [
    {
      id: 'shop_pill_small',
      displayName: '补气丹',
      description: '修为 ×40',
      goods: { resourceId: 'res_xiuwei', amount: 40 },
      priceType: 'res_lingshi',
      price: 80,
      purchaseLimit: 3,
      dailyRefresh: true,
    },
    {
      id: 'shop_yaodan_box',
      displayName: '妖丹礼盒',
      description: '妖丹 ×2',
      goods: { resourceId: 'res_yaodan', amount: 2 },
      priceType: 'res_lingshi',
      price: 150,
      purchaseLimit: 1,
      dailyRefresh: true,
    },
    {
      id: 'shop_lingpo_baihu',
      displayName: '白虎灵魄',
      description: '白虎灵魄 ×2',
      goods: { resourceId: 'res_lingpo_baihu', amount: 2 },
      priceType: 'res_lingshi',
      price: 200,
      purchaseLimit: 1,
      dailyRefresh: true,
    },
    {
      id: 'shop_lingpo_zhuque',
      displayName: '朱雀灵魄',
      description: '朱雀灵魄 ×2',
      goods: { resourceId: 'res_lingpo_zhuque', amount: 2 },
      priceType: 'res_lingshi',
      price: 240,
      purchaseLimit: 1,
      dailyRefresh: true,
    },
    {
      id: 'shop_lingpo_xuanwu',
      displayName: '玄武灵魄',
      description: '玄武灵魄 ×2',
      goods: { resourceId: 'res_lingpo_xuanwu', amount: 2 },
      priceType: 'res_lingshi',
      price: 240,
      purchaseLimit: 1,
      dailyRefresh: true,
    },
    {
      id: 'shop_lingpo_jiuweihu',
      displayName: '九尾狐灵魄',
      description: '九尾狐灵魄 ×2',
      goods: { resourceId: 'res_lingpo_jiuweihu', amount: 2 },
      priceType: 'res_lingshi',
      price: 280,
      purchaseLimit: 1,
      dailyRefresh: true,
    },
    {
      id: 'shop_lingshi_pack',
      displayName: '灵石宝袋',
      description: '灵石 ×500',
      goods: { resourceId: 'res_lingshi', amount: 500 },
      priceType: 'res_lingyu',
      price: 10,
      purchaseLimit: 10,
      dailyRefresh: false,
    },
    {
      id: 'shop_yaodan_essence',
      displayName: '妖丹精粹',
      description: '妖丹 ×5',
      goods: { resourceId: 'res_yaodan', amount: 5 },
      priceType: 'res_lingyu',
      price: 20,
      purchaseLimit: 5,
      dailyRefresh: false,
    },
  ],
  // 基础活动壳（V08-16）：登录活动编排 30 日累计登录（复用 LoginReward 领取逻辑，
  // 无第二套实现）；V0.8 永久开放（window null），窗口语义已配置化。
  activities: [
    {
      id: 'activity_login_01',
      displayName: '开服累计登录',
      type: 'login',
      contentRef: 'login_rewards',
      featureFlag: 'login_reward',
      window: null,
    },
  ],
  // 30 日累计登录奖励表（V08-14）：不要求连续、不补签、漏登不清零；
  // 逐档领取（第 30 档领完本轮结束，首发一次性不循环）。灵玉不在登录奖励投放（唯一产出=成就）。
  loginRewards: {
    totalDays: 30,
    tiers: [
      { day: 1, reward: { accountXp: 11, resources: { res_lingshi: 60, res_xiuwei: 22 } } },
      { day: 2, reward: { accountXp: 12, resources: { res_lingshi: 70, res_xiuwei: 24 } } },
      { day: 3, reward: { accountXp: 13, resources: { res_lingshi: 80, res_xiuwei: 26 } } },
      { day: 4, reward: { accountXp: 14, resources: { res_lingshi: 90, res_xiuwei: 28 } } },
      { day: 5, reward: { accountXp: 15, resources: { res_lingshi: 100, res_xiuwei: 30, res_yaodan: 1 } } },
      { day: 6, reward: { accountXp: 16, resources: { res_lingshi: 110, res_xiuwei: 32 } } },
      { day: 7, reward: { accountXp: 17, resources: { res_lingshi: 120, res_xiuwei: 34 } } },
      { day: 8, reward: { accountXp: 18, resources: { res_lingshi: 130, res_xiuwei: 36 } } },
      { day: 9, reward: { accountXp: 19, resources: { res_lingshi: 140, res_xiuwei: 38 } } },
      { day: 10, reward: { accountXp: 20, resources: { res_lingshi: 150, res_xiuwei: 40, res_yaodan: 2, res_lingpo_qinglong: 5 } } },
      { day: 11, reward: { accountXp: 21, resources: { res_lingshi: 160, res_xiuwei: 42 } } },
      { day: 12, reward: { accountXp: 22, resources: { res_lingshi: 170, res_xiuwei: 44 } } },
      { day: 13, reward: { accountXp: 23, resources: { res_lingshi: 180, res_xiuwei: 46 } } },
      { day: 14, reward: { accountXp: 24, resources: { res_lingshi: 190, res_xiuwei: 48 } } },
      { day: 15, reward: { accountXp: 25, resources: { res_lingshi: 200, res_xiuwei: 50, res_yaodan: 2, res_lingpo_baihu: 5 } } },
      { day: 16, reward: { accountXp: 26, resources: { res_lingshi: 210, res_xiuwei: 52 } } },
      { day: 17, reward: { accountXp: 27, resources: { res_lingshi: 220, res_xiuwei: 54 } } },
      { day: 18, reward: { accountXp: 28, resources: { res_lingshi: 230, res_xiuwei: 56 } } },
      { day: 19, reward: { accountXp: 29, resources: { res_lingshi: 240, res_xiuwei: 58 } } },
      { day: 20, reward: { accountXp: 30, resources: { res_lingshi: 250, res_xiuwei: 60, res_yaodan: 3, res_lingpo_zhuque: 5 } } },
      { day: 21, reward: { accountXp: 31, resources: { res_lingshi: 260, res_xiuwei: 62 } } },
      { day: 22, reward: { accountXp: 32, resources: { res_lingshi: 270, res_xiuwei: 64 } } },
      { day: 23, reward: { accountXp: 33, resources: { res_lingshi: 280, res_xiuwei: 66 } } },
      { day: 24, reward: { accountXp: 34, resources: { res_lingshi: 290, res_xiuwei: 68 } } },
      { day: 25, reward: { accountXp: 35, resources: { res_lingshi: 300, res_xiuwei: 70, res_yaodan: 3, res_lingpo_xuanwu: 5 } } },
      { day: 26, reward: { accountXp: 36, resources: { res_lingshi: 310, res_xiuwei: 72 } } },
      { day: 27, reward: { accountXp: 37, resources: { res_lingshi: 320, res_xiuwei: 74 } } },
      { day: 28, reward: { accountXp: 38, resources: { res_lingshi: 330, res_xiuwei: 76 } } },
      { day: 29, reward: { accountXp: 39, resources: { res_lingshi: 340, res_xiuwei: 78 } } },
      { day: 30, reward: { accountXp: 40, resources: { res_lingshi: 350, res_xiuwei: 80, res_yaodan: 5, res_lingpo_jiuweihu: 5 } } },
    ],
  },

  // 免费礼包初始表（V08-15，ECONOMY §5 免费子集）：成长（等级档）/章节（首通档）/
  // 境界（突破档）三线；priceType 恒 free、限购恒 1；前置链未领不可领后继。
  offers: [
    {
      id: 'offer_growth_lv5',
      displayName: '成长礼包·练气',
      description: '修行者达到 Lv.5',
      contents: { accountXp: 0, resources: { res_lingshi: 300, res_xiuwei: 50 } },
      priceType: 'free',
      price: 0,
      unlockCondition: { kind: 'playerLevel', level: 5 },
      purchaseLimit: 1,
      prerequisiteOfferId: null,
    },
    {
      id: 'offer_growth_lv10',
      displayName: '成长礼包·筑基',
      description: '修行者达到 Lv.10',
      contents: { accountXp: 0, resources: { res_lingshi: 600, res_xiuwei: 100, res_yaodan: 2 } },
      priceType: 'free',
      price: 0,
      unlockCondition: { kind: 'playerLevel', level: 10 },
      purchaseLimit: 1,
      prerequisiteOfferId: 'offer_growth_lv5',
    },
    {
      id: 'offer_growth_lv15',
      displayName: '成长礼包·凝丹',
      description: '修行者达到 Lv.15',
      contents: { accountXp: 0, resources: { res_lingshi: 900, res_xiuwei: 150, res_yaodan: 3 } },
      priceType: 'free',
      price: 0,
      unlockCondition: { kind: 'playerLevel', level: 15 },
      purchaseLimit: 1,
      prerequisiteOfferId: 'offer_growth_lv10',
    },
    {
      id: 'offer_growth_lv20',
      displayName: '成长礼包·圆满',
      description: '修行者达到 Lv.20',
      contents: { accountXp: 0, resources: { res_lingshi: 1500, res_xiuwei: 250, res_yaodan: 4 } },
      priceType: 'free',
      price: 0,
      unlockCondition: { kind: 'playerLevel', level: 20 },
      purchaseLimit: 1,
      prerequisiteOfferId: 'offer_growth_lv15',
    },
    {
      id: 'offer_chapter_qingyun',
      displayName: '章节礼包·青云外门',
      description: '通关全部青云外门关卡',
      contents: { accountXp: 0, resources: { res_lingshi: 500, res_lingpo_baihu: 5 } },
      priceType: 'free',
      price: 0,
      unlockCondition: { kind: 'chapterClear', chapterId: 'chapter_qingyun' },
      purchaseLimit: 1,
      prerequisiteOfferId: null,
    },
    {
      id: 'offer_chapter_yaochao',
      displayName: '章节礼包·妖潮深林',
      description: '通关全部妖潮深林关卡',
      contents: { accountXp: 0, resources: { res_lingshi: 800, res_lingpo_zhuque: 5 } },
      priceType: 'free',
      price: 0,
      unlockCondition: { kind: 'chapterClear', chapterId: 'chapter_yaochao' },
      purchaseLimit: 1,
      prerequisiteOfferId: 'offer_chapter_qingyun',
    },
    {
      id: 'offer_chapter_shiyao',
      displayName: '章节礼包·噬妖巢穴',
      description: '通关全部噬妖巢穴关卡',
      contents: { accountXp: 0, resources: { res_lingshi: 1200, res_lingpo_xuanwu: 5, res_lingpo_jiuweihu: 5 } },
      priceType: 'free',
      price: 0,
      unlockCondition: { kind: 'chapterClear', chapterId: 'chapter_shiyao' },
      purchaseLimit: 1,
      prerequisiteOfferId: 'offer_chapter_yaochao',
    },
    {
      id: 'offer_realm_zhuji',
      displayName: '境界礼包·筑基',
      description: '突破至筑基期',
      contents: { accountXp: 0, resources: { res_lingshi: 500, res_yaodan: 2 } },
      priceType: 'free',
      price: 0,
      unlockCondition: { kind: 'realmIndex', realmIndex: 1 },
      purchaseLimit: 1,
      prerequisiteOfferId: null,
    },
    {
      id: 'offer_realm_jindan',
      displayName: '境界礼包·金丹',
      description: '突破至金丹期',
      contents: { accountXp: 0, resources: { res_lingshi: 1000, res_yaodan: 4 } },
      priceType: 'free',
      price: 0,
      unlockCondition: { kind: 'realmIndex', realmIndex: 2 },
      purchaseLimit: 1,
      prerequisiteOfferId: 'offer_realm_zhuji',
    },
  ],
  upgrades: [
    {
      id: 'sword_damage_up',
      title: '剑意精进',
      description: '飞剑伤害 +5',
      maxStacks: 8,
      weight: 1,
      effects: [{ kind: 'addSwordDamage', value: 5 }],
    },
    {
      id: 'sword_cooldown_down',
      title: '御剑疾行',
      description: '飞剑发射间隔降低 12%',
      maxStacks: 6,
      weight: 1,
      effects: [{ kind: 'multiplySwordCooldown', value: 0.88 }],
    },
    {
      id: 'sword_count_up',
      title: '分光化剑',
      description: '每轮飞剑数量 +1',
      maxStacks: 7,
      weight: 1,
      effects: [{ kind: 'addSwordCount', value: 1 }],
    },
  ],
  // 功能解锁表（V10-02，GAME_LOOP §4 定案"章节内推进"校准，2026-10-05 用户确认）：
  // 首次进入=首页/关卡/基础法器（always）；修行/灵兽=通关第1关（首局结算后即可
  // 首次培养，GAME_LOOP §5 最短闭环）；图鉴=通关第2关、商店=通关第3关（每次重点
  // 介绍一个新系统）；礼包（奖励中心 offers 区）=通关第一章；活动=境界突破1。
  // 未解锁入口初始全部 hide（"首次进入不展示全部入口"）；show_condition 为配置
  // 可选路径，机制见 account/UnlockSystem。签到（活动壳 login）按 RETENTION
  // 每日登录语义保持日 1 可用，不绑 activities 解锁。
  unlocks: [
    { id: 'unlock_home', featureId: 'home', condition: { kind: 'always' }, lockedBehavior: 'hide', lockedText: '', featureFlag: null },
    { id: 'unlock_stage_select', featureId: 'stage_select', condition: { kind: 'always' }, lockedBehavior: 'hide', lockedText: '', featureFlag: 'stage_select' },
    { id: 'unlock_base_weapon', featureId: 'base_weapon', condition: { kind: 'always' }, lockedBehavior: 'hide', lockedText: '', featureFlag: null },
    { id: 'unlock_realm', featureId: 'realm', condition: { kind: 'stageClear', stageId: 'stage_mvp_01' }, lockedBehavior: 'hide', lockedText: '', featureFlag: null },
    { id: 'unlock_beast', featureId: 'beast', condition: { kind: 'stageClear', stageId: 'stage_mvp_01' }, lockedBehavior: 'hide', lockedText: '', featureFlag: null },
    { id: 'unlock_codex', featureId: 'codex', condition: { kind: 'stageClear', stageId: 'stage_qingyun_02' }, lockedBehavior: 'hide', lockedText: '', featureFlag: 'codex' },
    { id: 'unlock_shop', featureId: 'shop', condition: { kind: 'stageClear', stageId: 'stage_qingyun_03' }, lockedBehavior: 'hide', lockedText: '', featureFlag: 'shop' },
    { id: 'unlock_offers', featureId: 'offers', condition: { kind: 'chapterClear', chapterId: 'chapter_qingyun' }, lockedBehavior: 'hide', lockedText: '', featureFlag: null },
    { id: 'unlock_activities', featureId: 'activities', condition: { kind: 'realmIndex', realmIndex: 1 }, lockedBehavior: 'hide', lockedText: '', featureFlag: null },
  ],
  // 新手引导脚本（V10-03，GAME_LOOP §5 首发最短闭环：操作→自动攻击→拾取→
  // 三选一→结算→首次培养）。strong 仅限首次核心操作（移动/三选一/首次培养，
  // 白名单由配置校验强制）；自动攻击与拾取为弱提示（不阻塞战斗、可跳过）；
  // 结算为说明。改版时 version +1：老玩家（scriptVersion 非 0 且 ≠ 当前版本）
  // 不重卡（GuideSystem 版本迁移语义）。
  guide: {
    version: 1,
    // 用户决策（2026-10-05）：测试期关闭新手引导——玩家当前阶段只需要 UI/玩法，
    // 引导脚本与全部表现层保留，改回 true 即整体恢复（GAME_LOOP §5 功能不删）。
    enabled: false,
    entryStepId: 'guide_move',
    steps: [
      {
        id: 'guide_move',
        displayName: '移动',
        description: '拖动摇杆，带修行者走位',
        type: 'strong',
        scene: 'battle',
        trigger: 'guide_battle_started',
        completionEvent: 'guide_move_started',
        nextStepId: 'guide_attack',
        skippable: false,
        anchorId: 'player',
      },
      {
        id: 'guide_attack',
        displayName: '自动攻击',
        description: '本命法器自动索敌出手，无需操作',
        type: 'weak',
        scene: 'battle',
        trigger: 'guide_move_started',
        completionEvent: 'guide_attack_fired',
        nextStepId: 'guide_pickup',
        skippable: true,
        anchorId: 'player',
      },
      {
        id: 'guide_pickup',
        displayName: '拾取经验',
        description: '靠近掉落的经验灵珠即可拾取',
        type: 'weak',
        scene: 'battle',
        trigger: 'guide_attack_fired',
        completionEvent: 'guide_xp_collected',
        nextStepId: 'guide_levelup',
        skippable: true,
        anchorId: 'xp_gem',
      },
      {
        id: 'guide_levelup',
        displayName: '三选一',
        description: '升级后从三项中选择一项强化',
        type: 'strong',
        scene: 'battle',
        trigger: 'guide_xp_collected',
        completionEvent: 'guide_levelup_resolved',
        nextStepId: 'guide_settlement',
        skippable: false,
        anchorId: 'levelup_panel',
      },
      {
        id: 'guide_settlement',
        displayName: '结算',
        description: '结算发放账号经验与资源，可回首页培养',
        type: 'info',
        scene: 'battle',
        trigger: 'guide_levelup_resolved',
        completionEvent: 'guide_settlement_shown',
        nextStepId: 'guide_cultivate',
        skippable: true,
        anchorId: 'settlement_panel',
      },
      {
        id: 'guide_cultivate',
        displayName: '首次培养',
        description: '用结算所得去修行或灵兽页强化',
        type: 'strong',
        scene: 'home',
        trigger: 'guide_settlement_shown',
        completionEvent: 'guide_cultivate_opened',
        nextStepId: null,
        skippable: false,
        anchorId: 'nav_realm',
      },
    ],
  },
  // 音频分组（V10-05）：组音量基线 × 设置域主音量（bgm→bgmVolume，
  // skill/hit/ui→sfxVolume）为实际播放音量；并发上限与节流由 AudioMixer 纯逻辑
  // 判定（hit 高频组 90ms 节流，命中音不在热路径每帧触发）。占位音频资产名
  // （game/assets/audio/）与本表 clips 一一对应，正式音频随 V10-14 管线替换。
  audio: {
    // 用户决策（2026-10-05）：测试期音效整体后置——四组通道全部关闭（零播放），
    // 音效系统/分组/并发/节流实现保留，恢复播放把 enabled 改回 true 即可。
    channels: [
      { channel: 'bgm', volume: 70, maxConcurrent: 1, minIntervalMs: 0, enabled: false },
      { channel: 'skill', volume: 90, maxConcurrent: 4, minIntervalMs: 60, enabled: false },
      { channel: 'hit', volume: 60, maxConcurrent: 6, minIntervalMs: 90, enabled: false },
      { channel: 'ui', volume: 80, maxConcurrent: 3, minIntervalMs: 40, enabled: false },
    ],
    clips: [
      { id: 'bgm_main', channel: 'bgm' },
      { id: 'sfx_levelup', channel: 'skill' },
      { id: 'sfx_boss', channel: 'skill' },
      { id: 'sfx_hit', channel: 'hit' },
      { id: 'sfx_click', channel: 'ui' },
    ],
  },
  // 激励广告（V10-10，GAME_LOOP §6）：adUnitId 为用户前置（正式广告位 ID，
  // 空串 = 未配置 → 运行时模拟/失败路径）；复活每局 1 次/每日 3 次、无敌 2 秒、
  // 回复 50% maxHp、不可用场景为空（后续可配 Boss 关）。插屏默认关闭不配置。
  ads: {
    placements: [
      { id: 'ad_revive', type: 'rewarded', adUnitId: '', enabled: true },
      { id: 'ad_settlement', type: 'rewarded', adUnitId: '', enabled: true },
      { id: 'ad_daily', type: 'rewarded', adUnitId: '', enabled: true },
      { id: 'ad_reroll', type: 'rewarded', adUnitId: '', enabled: true },
    ],
    // 结算加成（V10-11）：victory/defeat 可选翻倍，补差 = floor(基础×2) − 本局已发；
    // abort 不提供；每日 3 次（存档审计）。
    settlementBonus: {
      placementId: 'ad_settlement',
      rewardMultiplier: 2,
      maxPerDay: 3,
      results: ['victory', 'defeat'],
    },
    // 每日广告资源位（V10-11，ECONOMY §6"每日有限资源"）：首页观看领灵石，
    // 每日 2 次、间隔 10 分钟（占位数值，产消复核见 CONFIG.md 广告位投放表）。
    dailyResource: {
      placementId: 'ad_daily',
      resources: { res_lingshi: 150 },
      maxPerDay: 2,
      cooldownMinutes: 10,
    },
    // 三选一"换一批"（V10-11 追加，用户定案）：每局 2 次，广告失败不扣次数。
    reroll: {
      placementId: 'ad_reroll',
      maxPerBattle: 2,
    },
    revive: {
      placementId: 'ad_revive',
      maxPerBattle: 1,
      maxPerDay: 3,
      invulnerableSeconds: 2,
      hpRestoreRatio: 0.5,
      disabledStageIds: [],
    },
  },
});
